### ISSUE TITLE
"mutex destroyed while busy" on MSVC with async socket

### ISSUE THREAD

**Issue by mporsch** [mporsch/sockpuppet#1]
see e.g. https://travis-ci.com/mporsch/sockpuppet/jobs/262203120#L260

**Comment by paulocoutinhox** [comment]
It was solved?

**Comment by mporsch** [comment]
I only encountered that issue in the Travis MSVC-based test runs. Last failure was a year ago and there have been lots of test runs without issues in the meantime.
I have not determined the root cause of that exception and could never reproduce it on my machine with Mingw.

So, is it solved? - Dunno :)
Not even sure if it ever was an issue, or just some temporary bug in the MSVC toolchain.

**Comment by mporsch** [comment]
Not seen since, so probably a non-issue.
