### ISSUE TITLE
Android and iOS support

### ISSUE THREAD

**Issue by paulocoutinhox** [mporsch/sockpuppet#2]
Hi,

It support android and ios?

Thanks.

**Comment by mporsch** [comment]
You tell me! :)
Android probably not, telling from my impression of workarounds needed in other cross-platform libraries.
Might give it a try on iOS, though.

I'll leave this issue open, so you can provide results if you give it a try.

**Comment by mporsch** [comment]
It's been 3 months without feedack, so I'm closing this issue. Feel free to add a discussion if you gain new insights, though.
